name: 'miamitech'
version: 0.0.1
description: A minimal web server using the shelf package.
author: David Notik dave@woven.co
homepage: http://miamitech.org
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.12.0 <0.13.0'
  shelf: '>=0.5.5 <0.6.0'
  mustache: '>=0.1.8 <0.2.0'
  firebase: '>=0.2.0+1 <0.3.0'
  http: '>=0.11.1+1 <0.12.0'
  intl: ">=0.11.10 <0.12.0"
  shelf_route: '>=0.11.0+1 <0.12.0'
  shelf_exception_response: '>=0.1.1 <0.2.0'